### ISSUE TITLE
[BUG] Unable To Debug Service Fabric Remoting Service With .NET 6

### ISSUE THREAD

**Issue by websitewill** [microsoft/service-fabric#1356] opened 2022-05-11 14:06 UTC
**Bug:**
  
**Describe the issue:**
When updating a service to use .NET 6, I am no longer able to debug when "Attach to process". All I get now is "Application is in break mode" with no stack trace or anything useful. Reverting to .NET 5 corrects the issue.

**Describe as best as possible how to reproduce the issue:**
Migrate a service to .NET 6, put a breakpoint on a service method, attach to the process (or use a Debugger.Launch(). The debugger will attach, but you can't do anything with it.

**Service Fabric Version:**
9.0.1017.9590

**Hosted on Azure or On-Prem:**
On-Prem. 1-Node Dev Cluster

**Comment by ArtemSPavlenko** [comment] 2022-10-04 09:51
Hi!

In our case, we are unable to debug actors running on service fabric when targeting .NET 6. I have also made a post on this issue regarding DAPR actors: https://github.com/dapr/dotnet-sdk/issues/811

It seems that in .NET 6 you are unable to debug actors in general. When trying to do so, Visual Studio says "Application is in break mode" followed by "Your app has entered a break state, but no code is currently executing that is supported by the selected debug engine".

Any ideas to why this is?

**Comment by websitewill** [comment] 2022-10-04 11:17
Hi Artem,
I am pretty sure that nobody is monitoring this at all. I still have the issue and, as you can see, zero responses.

Will

**Comment by ArtemSPavlenko** [comment] 2022-10-04 11:31
Hi Will,

I see.. This issue really needs to be looked into, I will see what I can do to raise awareness!

Artem

**Comment by ArtemSPavlenko** [comment] 2022-10-11 13:17
Hi @websitewill, 

Are you able to debug the actor service if the application is published in debug mode? 

![image](https://user-images.githubusercontent.com/43640111/195101053-d605caf8-ee20-4a79-950b-6da76c5e48aa.png)

**Comment by WhitWaldo** [comment] 2022-12-08 06:10
I'm just another SF customer, but I'm unable to reproduce your issue. The application starts locally as expected and breakpoints I set are hit, whether in methods called via remoting or by the actor itself. 

Have you tried resetting the local development cluster? Maybe repairing VS?

**Comment by ArtemSPavlenko** [comment] 2022-12-08 07:52
This issue is resolved for me @WhitWaldo, I was able to debug the application when debugging by new instance! 😄

**Comment by yashagarwal23** [comment] 2022-12-22 09:42
Actually, for service remoting, SF creates some classes dynamically (using System.Reflection.Emit apis) that acts as proxy between the remoting caller service and the callee service. For .Net 6, the VS debugger is not able to load metadata for these proxy classes and thus the application goes into break mode when we try to debug a service remoting call.

It turns out .NET runtime team did some changes in the System.Reflection.Emit module and as a side effect .NET 6 runtime doesn’t generate metadata for dynamic classes unless a debugger is attached https://github.com/dotnet/runtime/issues/62977#issuecomment-1186149824.
This has been fixed now - https://github.com/dotnet/runtime/pull/77322. the latest .NET 6 release should contain the fix.

**Comment by yashagarwal23** [comment] 2022-12-28 09:48
I am closing this issue for now. Please reopen it if required.

**Closed by yashagarwal23** 2022-12-28 09:48 UTC
Labels: status-last6months
