### ISSUE TITLE
[BUG] Cannot install SDK 7.0.1816

### ISSUE THREAD

**Issue by shaohaolin** [microsoft/service-fabric#1462] opened 2023-09-15 21:56 UTC
**Describe the bug**
Cannot install SDK 7.0.1816 

**To Reproduce**
I was able to install MicrosoftServiceFabric.10.0.1816.9590 successfully however, when I ran the wizard. It gave me an error. 

**Expected behavior**

**Observed  behavior**:

**Screenshots**

**Service Fabric Runtime Version:** 
10.0.1816.9590

**Environment:**
Windows 11

![image](https://github.com/microsoft/service-fabric/assets/6677092/06ea555c-29fa-4478-b00b-948fb99e8cbf)
---
Assignees: /cc @microsoft/service-fabric-triage

**Comment by negberts** [comment] 2023-09-19 07:24
Same here... 3 days and no response... Service Fabric is so alive!

**Comment by jackbond** [comment] 2023-09-19 15:01
They put out a major new release, and this was literally the only announcement...

https://azure.microsoft.com/en-us/updates/azure-service-fabric-100-release/

I can't get my company off of service fabric fast enough.

**Comment by negberts** [comment] 2023-09-19 17:47
@jackbond the nuget package was there way before the release10 branch was merged into the master branch :'-) In the master branch there was nothing to find about 10 when the nuget packages were out....

**Comment by specialforest** [comment] 2023-09-19 18:49
I see the following messages in an installation log, not sure if they related to the actual issue:
```
Error: could not load custom action class Microsoft.ServiceFabric.SdkRuntimeCompatibilityCheck.CompatibilityCheckCA from assembly: SdkRuntimeCompatibilityCheck
System.IO.FileLoadException: Could not load file or assembly 'SdkRuntimeCompatibilityCheck, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'SdkRuntimeCompatibilityCheck, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.AppDomain.Load(String assemblyString)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.GetCustomActionMethod(Session session, String assemblyName, String className, String methodName)

...
MSI (c) (E0:E4) [11:36:00:367]: Product: Microsoft Azure Service Fabric SDK -- Installation failed.

MSI (c) (E0:E4) [11:36:00:375]: Windows Installer installed the product. Product Name: Microsoft Azure Service Fabric SDK. Product Version: 7.0.1816.9590. Product Language: 1033. Manufacturer: Microsoft Corporation. Installation success or error status: 1603.
```

**Comment by jberezanski** [comment] 2023-09-25 15:43
I've poked inside the installation MSI. It seems that the `SdkRuntimeCompatibilityCheck.dll` assembly, which fails to load, is delay-signed. It would seem that the dll embedded in the MSI was taken from an incomplete, unofficial or otherwise not fully signed build.
```
PS C:\> Get-FileHash "C:\Users\Admin\AppData\Local\Temp\CompatibilityCheckCA_DLL.dll"

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          F42EB04AE05A997CB0730BCDB4BD5436C4AAC64038F04FDD99B55F9A4814B431       C:\Users\Admin\AppData\Local\Temp\CompatibilityCheckCA_DLL.dll

PS C:\> Get-FileHash "C:\Users\Admin\AppData\Local\Temp\CompatibilityCheckCA_DLL\SdkRuntimeCompatibilityCheck.dll"

Algorithm       Hash                                                                   Path
---------       ----                                                                   ----
SHA256          17C919363C827A8C9968FE05153E0E1E6D59D7EFEC12CA599FD72EBA9A2472CB       C:\Users\Admin\AppData\Local\Temp\CompatibilityCheckCA_DLL\SdkRuntimeCompatibilityCheck.dll

PS C:\> & 'C:\Program Files (x86)\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\sn.exe' -vf "C:\Users\Admin\AppData\Local\Temp\CompatibilityCheckCA_DLL\SdkRuntimeCompatibilityCheck.dll"

Microsoft (R) .NET Framework Strong Name Utility  Version 4.0.30319.0
Copyright (c) Microsoft Corporation.  All rights reserved.

C:\Users\Admin\AppData\Local\Temp\CompatibilityCheckCA_DLL\SdkRuntimeCompatibilityCheck.dll is a delay-signed or test-signed assembly
```

**Comment by derwee** [comment] 2023-09-26 11:51
Has anybody managed to get around this?

**Comment by jberezanski** [comment] 2023-09-26 12:41
There is a workaround - strong name verification can be disabled for this specific assembly, using the `sn.exe` tool from the .NET Framework SDK. The SDK can be installed using Chocolatey, or manually by [downloading](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer) and running the installer.

Here is a full example (in PowerShell with admin rights):
```powershell
choco install -y netfx-4.8-devpack
& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe" -Vr "SdkRuntimeCompatibilityCheck,31BF3856AD364E35"
choco install -y service-fabric-sdk
```

**Comment by derwee** [comment] 2023-09-26 12:55
> There is a workaround - strong name verification can be disabled for this specific assembly, using the `sn.exe` tool from the .NET Framework SDK. The SDK can be installed using Chocolatey, or manually by [downloading](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer) and running the installer.
> 
> Here is a full example (in PowerShell with admin rights):
> 
> ```powershell
> choco install -y netfx-4.8-devpack
> & "${Env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe" -Vr "SdkRuntimeCompatibilityCheck,31BF3856AD364E35"
> choco install -y service-fabric-sdk
> ```
> 
> (`31BF3856AD364E35` is the public key token of the SdkRuntimeCompatibilityCheck assembly.)

Great I'll give it a shot,

Thank you!

**Comment by SnowdenNeuroverse** [comment] 2023-09-29 01:43
> There is a workaround - strong name verification can be disabled for this specific assembly, using the `sn.exe` tool from the .NET Framework SDK. The SDK can be installed using Chocolatey, or manually by [downloading](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer) and running the installer.
> 
> Here is a full example (in PowerShell with admin rights):
> 
> ```powershell
> choco install -y netfx-4.8-devpack
> & "${Env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe" -Vr "SdkRuntimeCompatibilityCheck,31BF3856AD364E35"
> choco install -y service-fabric-sdk
> ```
> 
> (`31BF3856AD364E35` is the public key token of the SdkRuntimeCompatibilityCheck assembly.)

Worked perfectly, you're a life saver, thank you!

**Comment by stuart-trotter-xdna** [comment] 2023-09-29 01:45
> There is a workaround - strong name verification can be disabled for this specific assembly, using the `sn.exe` tool from the .NET Framework SDK. The SDK can be installed using Chocolatey, or manually by [downloading](https://dotnet.microsoft.com/en-us/download/dotnet-framework/thank-you/net48-developer-pack-offline-installer) and running the installer.
> 
> Here is a full example (in PowerShell with admin rights):
> 
> ```powershell
> choco install -y netfx-4.8-devpack
> & "${Env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe" -Vr "SdkRuntimeCompatibilityCheck,31BF3856AD364E35"
> choco install -y service-fabric-sdk
> ```
> 
> (`31BF3856AD364E35` is the public key token of the SdkRuntimeCompatibilityCheck assembly.)

Worked perfectly, you're a life saver, thank you!

**Comment by williamoconnorme** [comment] 2023-09-29 12:40
I'm experiencing a similar issue to what @jberezanski has found with SdkRuntimeCompatibilityCheck and strong name validation failing.

```
Error: could not load custom action class Microsoft.ServiceFabric.SdkRuntimeCompatibilityCheck.CompatibilityCheckCA from assembly: SdkRuntimeCompatibilityCheck
System.IO.FileLoadException: Could not load file or assembly 'SdkRuntimeCompatibilityCheck, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)
File name: 'SdkRuntimeCompatibilityCheck, Version=10.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' ---> System.Security.SecurityException: Strong name validation failed. (Exception from HRESULT: 0x8013141A)
The Zone of the assembly that failed was:
MyComputer
   at System.Reflection.RuntimeAssembly._nLoad(AssemblyName fileName, String codeBase, Evidence assemblySecurity, RuntimeAssembly locationHint, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoadAssemblyName(AssemblyName assemblyRef, Evidence assemblySecurity, RuntimeAssembly reqAssembly, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean throwOnFileNotFound, Boolean forIntrospection, Boolean suppressSecurityChecks)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, IntPtr pPrivHostBinder, Boolean forIntrospection)
   at System.Reflection.RuntimeAssembly.InternalLoad(String assemblyString, Evidence assemblySecurity, StackCrawlMark& stackMark, Boolean forIntrospection)
   at System.AppDomain.Load(String assemblyString)
   at Microsoft.Deployment.WindowsInstaller.CustomActionProxy.GetCustomActionMethod(Session session, String assemblyName, String className, String methodName)
```

The workaround unfortunately won't work for me as my use case is that the SDK is installed through a winget package which can't execute binaries such as sn.exe before installing the SDK.

**Comment by Hua688** [comment] 2023-10-02 16:59
The workaround didn't work for me in the beginning after I run the sn inside "Developer Command Prompt for VS 2022". and "Sn -Vl" shows correct bypass in that window.

However, randomly when I open "x64 Native Tools Command Prompt for VS 2022" and run "SN -Vl", the bypass is not there. So I apply the workaround again in this window. After that everything start to work.

**Comment by jberezanski** [comment] 2023-10-03 17:04
Correct, the 64-bit version of sn.exe must be used. That is why I provided the full path in my post above.

**Comment by samedder** [comment] 2023-10-13 02:01
> The workaround unfortunately won't work for me as my use case is that the SDK is installed through a winget package which can't execute binaries such as sn.exe before installing the SDK.

@williamoconnorme what winget package are you using that installs Service Fabric?

**Comment by tuhland** [comment] 2023-10-13 07:07
The package is _Microsoft.ServiceFabricRuntime_.

But as you can see with `winget search "Microsoft.ServiceFabricRuntime" --versions` it's not well maintained. The 9.x version for example is not the latest refresh of that version.

**Comment by williamoconnorme** [comment] 2023-10-13 13:21
> There seems to be no package for the SDK.

It's now possible to add the SDK as a winget package since winget 1.6 released which supports package dependencies for installing the runtime first. This is similar to how the chocolatey package works.

However because of the issue mentioned here with the SDK installer, it's not possible to pass build validation for the winget package repository. Some more details in my pull request here: https://github.com/microsoft/winget-pkgs/pull/120285

I'll be reopening my PR once Microsoft resolves issues with the available 7.0.1816 SDK

**Comment by samedder** [comment] 2023-10-13 21:51
Hey Everyone,

I wanted to let you know internally we are aware of the issue and have reproduced this. Sorry for the delay in responses here. I'll post any updates as we investigate.

**Comment by johncrim** [comment] 2023-10-19 01:06
@williamoconnorme - thank you for adding the winget package, 10 OSS points for you. I was just looking for something like that a couple hours ago.

I assume your winget pkg includes the properly SNed assembly?

**Comment by mortb** [comment] 2023-10-19 10:21
> Hey Everyone,
> 
> I wanted to let you know internally we are aware of the issue and have reproduced this. Sorry for the delay in responses here. I'll post any updates as we investigate.

Any update on this? I need to install the SDK to update one of our services.

**Comment by johncrim** [comment] 2023-10-19 16:52
@jberezanski - thank you very much for figuring out and sharing the workaround.

@mortb - just follow the workaround that @jberezanski shared above - run:

```ps`
& "${Env:ProgramFiles(x86)}\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\sn.exe" -Vr "SdkRuntimeCompatibilityCheck,31BF3856AD364E35"
```

Before installing the v7 SF SDK.

**Comment by victor-gutemberg** [comment] 2023-10-19 17:53
Also had the same issue while installed the latest version of the Service Fabric SDK.

**Comment by mortb** [comment] 2023-10-20 09:25
This worked for me:

1. Download SDK installer from page https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started
2. Open command prompt as *administrator* 
3. Write `cd "%programfilesx86%\Microsoft SDKs\Windows\v10.0A\bin\NETFX 4.8 Tools\x64\"` to go to the directory for the *needed* version of sn 
4. Write `sn.exe" -Vr "SdkRuntimeCompatibilityCheck,31BF3856AD364E35"`
5. Install SDK (I installed it from the same command prompt window)

@samedder it seems quite clear that ServiceFabric is no longer a  product that Microsoft has any focus on.
My team is considering leaving the platform. I would suggest to others that they consider their options as well.

**Comment by jagilber** [comment] 2023-10-25 17:27
until a new sf sdk version is released for issue in sdk 7.0.1816, the sf 9.1 cu6 sdk can also be used if not wanting to run sn: https://github.com/Azure/Service-Fabric-Troubleshooting-Guides/blob/master/Known_Issues/service-fabric-10.0-sdk-7.0.1816-installation-failure.mdInstall Service Fabric 9.1 CU6 SDK

[9.1 CU6 SDK release notes](https://github.com/microsoft/service-fabric/blob/master/release_notes/Service_Fabric_ReleaseNotes_91CU6.md)
[9.1 CU6 SDK runtime download](https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.9.1.1851.9590.exe)
[9.1 CU6 SDK sdk download](https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabricSDK.6.1.1851.msi)

**Comment by samedder** [comment] 2023-10-26 21:32
We have another build of the SDK with this issue fixed and are in the process of verifying and releasing this build now.

**Comment by PG23I** [comment] 2023-11-01 22:06
@samedder Any updates on what the ETA is looking like?

**Comment by jagilber** [comment] 2023-11-06 19:09
## Resolution

The fix for this issue is now released in Service Fabric 10.0 SDK (7.0.1949) release. Please download the latest SDK from [Install the SDK and tools](https://learn.microsoft.com/en-us/azure/service-fabric/service-fabric-get-started#install-the-sdk-and-tools).

[Service Fabric 10.0 Runtime (10.0.1949.9590)](https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabric.10.0.1949.9590.exe)

[Service Fabric 10.0 SDK (7.0.1949)](https://download.microsoft.com/download/b/8/a/b8a2fb98-0ec1-41e5-be98-9d8b5abf7856/MicrosoftServiceFabricSDK.7.0.1949.msi)

**Closed** 2023-11-07 20:49 UTC
Labels: type-code-defect

**Comment by williamoconnorme** [comment] 2023-11-07 23:31
@samedder @johncrim Adding that the SDK is now available for the first time through winget with version 7.0.1949

```winget install Microsoft.ServiceFabricSDK```

I've updated the runtime package also which is installed as a dependency with the command above. For the runtime on its own use: 

```winget install Microsoft.ServiceFabricRuntime```

**Comment by tuhland** [comment] 2023-11-08 09:16
@williamoconnorme Love that, thank you a lot! 
It's way easier to tell our devs to run a command to update, instead of "Go find the links, then download, then execute them in the terminal".

2 issues that occurred while testing this:

- If I run the install command with `--force` while already having a SDK installed, I get file access denied errors. I hope this won't be an issue with installing an actual update.
- It only works in Powershell 5 for me. In version 7 it fails with:  
`Powershell Execution Policy: Get-ExecutionPolicy : The 'Get-ExecutionPolicy' command was found in the module 'Microsoft.PowerShell.Security', but
the module could not be loaded. For more information, run 'Import-Module Microsoft.PowerShell.Security'`.
Looks like there is a hidden dependency or something. It still fails after running the import command from the message.

**Comment by taurheim** [comment] 2024-07-12 18:55
This issue is still occurring
