### ISSUE TITLE
Remove-ServiceFabricApplication -ForceRemove is useless

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#1038] opened 2020-09-27 20:55 UTC
Service Fabric Runtime Version: 

Environment: Azure

Description: -ForceRemove parameter of Remove-ServiceFabricApplication cmdlet doesn't work

Observed behavior: 

Cluster takes hours to actually remove application

Expected Behavior:

Application should be fully deleted within 60 seconds (and that's generous)

**Comment by gkhanna79** [comment] 2020-10-16 17:27
@jackbond Can you please share the traces to understand why it took that long to delete the application?

@motanv FYI

**Comment by jackbond** [comment] 2020-10-16 17:38
I don't have any traces, and I deleted the entire cluster just to uninstall the app. I believe the app got into a hung state because the nodes we're experiencing low memory. Here's what I can tell you. After calling Remove-ServiceFabricApplication with -ForceRemove, the cluster clearly started the removal process, but some of the processes in the app refused to die. Now, after working with SF for 3+ years, I'm pretty obsessed about respecting the CancellationToken, so that's definitely not the problem. After seeing some processes still running, I logged onto every node in the cluster, and killed every offending process with a powershell script. Unfortunately SF restarts them. A cluster shouldn't relaunch services for an app that has been marked for deletion. Watching SF restart the processes, I decided that I would delete the app binaries to prevent that from happening (and yes I realize I'm doing something that could seriously confuse SF.) Even after removing my app's binaries from every node, the app delete was still stuck.

**Comment by motanv** [comment] 2020-10-22 06:35
Hello @jackbond, it is unfortunate that Remove-ServiceFabricApplication API did not help in your case. We could try the below when things look stuck:
1. Remove-ServiceFabricReplica -ForceRemove -PartitionId 5d0468fc-d8d9-475c-8d0a-6ad300186cb3 -ServiceName fabric:/TestApp1/PersistServ -ReplicaOrInstanceId 132478205422575752
2. Restart-ServiceFabricNode -NodeName Node0

The first one above (Remove-ServiceFabricReplica -ForceRemove) would try to kill the process on the node that is hosting the replica  132478205422575752 of partition 5d0468fc-d8d9-475c-8d0a-6ad300186cb3 of service fabric:/TestApp1/PersistServ of application fabric:/TestApp1.

The second one (Restart-ServiceFabricNode) will kill the Fabric.exe running on the node and that should kill all service host processes on the node.

From your description, it appears that the machine where the SF node (basically Fabric.exe and service host processes) was running had low memory. If we can have a repro of the issue, we could work on finding the root cause and if needed improve the Remove-ServiceFabricApplication API. Does it repro often or are you able to repro? If yes, would you be willing to work with me to find out the root cause and help us better the API?

**Comment by jackbond** [comment] 2020-10-23 18:24
If I needed to reproduce this on the fly, this is how I would go about doing it.

Create a generic SF stateless service type that allocates 100MB of memory and doesn't release it. Then create an instance of that service with 500 partitions and an ActivationMode of ExclusiveProcess. Now that your cluster is hosed by that application, delete the application with -ForceRemove. If it works great, but sometimes it doesn't, even if...

1) You manually go onto the cluster and kill every instance of the service on every node. SF keeps trying to restart them (why restart a service for an app that has been marked for deletion.)
2) Delete the application's binaries, from every node, so SF can't restart them

What was clear from talking to the guys in support is that THEY'RE FRUSTRATED by SF's woeful app delete code. How bad is it? "I cannot delete my application or service" is a category when creating a service ticket.  Seriously???

![image](https://user-images.githubusercontent.com/2799232/97039460-54752700-1521-11eb-958d-55d84235e7c8.png)

**Comment by masnider** [comment] 2020-11-13 00:43
It's a common category, since user errors or bugs like the one you describe (a leak which starves the control plane hosted in your cluster and prevents management operations) are common, and the support folks have a playbook for helping diagnose such issues. 

Guidelines in the SF best practices (which I'm sure you've read through and applied) specifically recommend segmenting the SF system services onto their own node type, specifically so that such leaks won't starve the control plane. SF also provides resource governance functionality specifically to restrict CPU and Memory consumption of workloads so that they can't consume more than you expect. Generally either of those practices would prevent the behavior you describe above. We also tend to recommend local testing and chaos testing to flush out other lifecycle issues like the one you described (good to hear that you're respecting cancellation tokens).

As a corollary: Try an experiment - completely deprive your OS of some resource. Memory, CPU, something like that. Then try to perform some control operation (pick any you like - install some new program, launch something, try to uninstall something, copy a large file, whatever) and observe what happens. My bet is that it doesn't perform well, or could even fail! That's what computers do when you starve them of available resources. That you can do the same with a bunch of computers at once, and starve the control plane running in those machines shouldn't surprise you.

If you expect the self-hosted control plane to work when it has no resources, that seems to either be a misunderstanding about how SF works, or a willful misinterpretation. You've had years of working with Service Fabric, so I'm not sure either of these is likely. If you have some other theory for why this would be surprising to you, I'd be interested in hearing it. 

You may also be happy to hear (if you haven't already by attending our regular community calls) that this is part of the reason why we're considering moving the system services outside the cluster entirely, such that a misbehaving application can't impact them. If the app still had some bug where it wouldn't close down on its own though, that could still cause issues. 

If you'd like our help in determining why your -real- application was unable to be deleted, please work with us to get a repro and/or traces. Without that, I'm going to close this issue for now. If you get a repro and traces and want to work with us to help understand the issue, please reopen with that info.

**Closed by masnider** 2020-11-13 00:43 UTC
Labels: area-SystemServices

**Comment by jackbond** [comment] 2020-11-13 19:22
While I appreciate sarcasm as much as the next guy, the reality is, while I may be an unprofessional jerk, YOU DON'T GET TO BE. Allow me relay some more "legitimate information" to you. I've included the script sent to me by Azure support when I initially filed the support ticket below. See what it does? It deletes resources starting at the replica level. If as you so smugly implied that the problem were simply the resource plane being resource deprived, the script shouldn't do a better job than calling Remove-ServiceFabricApplication, and yet it does. Also, if you had actually read my above messages, you would have learned that I remoted in to EVERY node, and manually killed the application's processes, so RESOURCE DEPLETION WAS NOT THE PROBLEM.

Not that it's particularly relevant, but given that this problem can crop up in DEVELOPMENT clusters, setting up multiple node types just to be able to delete a rogue app is not worth the expense.

```
foreach($node in $nodes)
{
    $replicas = Get-ServiceFabricDeployedReplica -NodeName $node.NodeName -ApplicationName "fabric:/MyAppName"
 
    foreach ($replica in $replicas)
    {
        Remove-ServiceFabricReplica -ForceRemove -NodeName $node.NodeName -PartitionId $replica.Partitionid -ReplicaOrInstanceId $replica.ReplicaOrInstanceId
    }
} 
```

**Comment by masnider** [comment] 2020-11-17 00:40
Nothing I said here as sarcastic. Apologies if it somehow came off that way.

Resource depletion was the scenario you described, so that was the scenario I responded to. If that didn't describe your scenario, please re-describe your actual scenario.

Again, if you have a repro you want us to look at, please capture the traces and let us know here by reopening the issue, or open a support ticket and be sure to ask for an RCA.

**Comment by jackbond** [comment] 2020-11-17 01:03
The issue was originally caused by a low memory situation. I had code which would create a service which normally would have a few partitions and ServicePackageActivationMode.ExclusiveProcess. We had an issue that in some rare cases, the service would be created with hundreds of partitions, and no surprise it would overload the cluster. That issue has since been resolved, BUT in those cases when it did happen, the cluster was unrecoverable because -ForceRemove didn't work properly.

Not great, but if a cluster has been overloaded, it's somewhat understandable that all bets are off. But, and this is the key issue, in an attempt to recover the cluster before nuking it entirely, I remoted into every node on the cluster and manually killed every process associated with the application. Unfortunately, SF kept restarting them, even though Remove-ServiceFabricApplication had been run, AND the app's status in SF explorer showed "deleting".

Finally to prevent SF from restarting the app, I l remoted into every cluster, and literally deleted the application's binaries. Admittedly, that may confuse SF, but it most definitely stopped SF from restarting the services, and at that point resource depletion was no longer an issue. Unfortunately, SF was still hung attempting to delete the app, so I simply deleted the cluster and started from scratch.

My primary focus that day was getting the cluster back up and running, so I do not have any traces.
