### ISSUE TITLE
Unable to install Azure Service Fabric Runtime 7.0.x

### ISSUE THREAD

**Issue by supritap** [microsoft/service-fabric#497] opened 2020-02-21 22:42 UTC
I'm unable to install Service Fabric Runtime version 7.0.x from WPI or from command prompt or with a directly downloaded .exe file. Install of Service Fabric Runtime 6.X works fine.

Install of Service Fabric SDK fails due to failed install of Service Fabric Runtime. WPI log shows the following errors: 
DownloadManager Error: 0 : Error loading rating files: System.Xml.XmlException: Root element is missing.
   at System.Xml.XmlTextReaderImpl.Throw(Exception e)
   at System.Xml.XmlTextReaderImpl.ThrowWithoutLineInfo(String res)
   at System.Xml.XmlTextReaderImpl.ParseDocumentContent()
   at System.Xml.XmlTextReaderImpl.Read()
   at System.Xml.XmlLoader.Load(XmlDocument doc, XmlReader reader, Boolean preserveWhitespace)
   at System.Xml.XmlDocument.Load(XmlReader reader)
   at System.Xml.XmlDocument.Load(String filename)
   at Microsoft.Web.PlatformInstaller.ProductServiceImpl.GetAppRatings()

and 
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c wmic product where name="Microsoft Azure Service Fabric" call uninstall'. Process Id: 7364
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 7.0.466' is '0'
DownloadManager Information: 0 : Ignoring exit code '0' for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop KtlLogger'. Process Id: 4452
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 7.0.466' is '1062'
DownloadManager Information: 0 : Ignoring exit code '1062' for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'. Commandline is: 'C:\WINDOWS\sysnative\cmd.exe /c sc.exe stop LeasLayr'. Process Id: 7240
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 7.0.466' is '1062'
DownloadManager Information: 0 : Ignoring exit code '1062' for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'
DownloadManager Information: 0 : Starting EXE command for product 'Microsoft Azure Service Fabric Runtime - 7.0.466'. Commandline is: 'C:\Users\...\AppData\Local\Microsoft\Web Platform Installer\installers\ServiceFabricRuntime_7_0_CU3\163A93036CA2217E4E0B17AD7F2F63CCE369B9C3\MicrosoftServiceFabric.7.0.466.9590.exe /AcceptEULA'. Process Id: 12884
DownloadManager Information: 0 : Install exit code for product 'Microsoft Azure Service Fabric Runtime - 7.0.466' is '-532462766'
DownloadManager Error: 0 : Install return code for product 'Microsoft Azure Service Fabric Runtime - 7.0.466' is Failure

From exe: 
\MicrosoftServiceFabric.7.0.464.9590.exe" /AcceptEULA

Unhandled Exception: System.TypeInitializationException: The type initializer for 'Microsoft.ServiceFabric.InstallFabricRuntime.Program' threw an exception. ---> System.ArgumentNullException: Value cannot be null.
Parameter name: path1
   at System.IO.Path.Combine(String path1, String path2)
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program..cctor()
   --- End of inner exception stack trace ---
   at Microsoft.ServiceFabric.InstallFabricRuntime.Program.Main(String[] args)

From command prompt:
webpicmd.exe /Install /AcceptEula /SuppressReboot /Products:MicrosoftAzure-ServiceFabric-CoreSDK

...
Started installing: 'Microsoft Azure Service Fabric Runtime - 7.0.466'
Downloaded: 'Microsoft Azure Service Fabric SDK - 4.0.466'
Install completed (Failure): 'Microsoft Azure Service Fabric Runtime - 7.0.466'
ServiceFabricRuntime_7_0_CU3 : Failed.
…

- I don't see the InstallFabricRuntime.log (Log Location: %windir%\Temp\InstallFabricRuntime.log, but I don't see the file under Temp)
- I have powershell version 5. I also placed powershell.exe and powershell shortcut in windows/system32
- I have enabled Remote Registry
- I've uninstalled previous version of service fabric (6.0), deleted the service fabric folder from C:/Program Files
- Ran sc stop com.docker.service 
What am I missing?

**Comment by SKAUL05** [comment] 2020-06-25 11:26
Any updates on this issue?

**Comment by maburlik** [comment] 2020-08-05 01:40
Closing since the issue has not received a reply. Please try the newest 7.1 release and open another thread if you are still hitting issues.

**Closed by maburlik** 2020-08-05 01:40 UTC

**Comment by SinueeHernandez** [comment] 2020-12-08 21:32
I have this same issue and confirmed the registry I don't have a TEMP entry.  I'm trying to install version 7.2.445.9590
