### ISSUE TITLE
When Ubuntu 18.04 (Bionic beaver) will be supported?

### ISSUE THREAD

**Issue by nockawa** [microsoft/service-fabric#91] opened 2018-04-19 12:29 UTC
I've tried to install Service Fabric on my Development Environment which is Ubuntu 18.04 and the following scrip failed
```bash
sudo curl -s https://raw.githubusercontent.com/Azure/service-fabric-scripts-and-templates/master/scripts/SetupServiceFabric/SetupServiceFabric.sh | sudo bash
```
I've removed the check of the OS Version (Xenial) but the dependencies still won't install...

I know the documentation strictly specify Xenial, but I was wondering if the 18.04 will be supported soon or if there's a workaround in the meantime.

Thanks

**Comment by bpm-ms** [comment] 2018-04-19 17:48
@anmolah Do you have any timeline for this?

**Comment by anmolah** [comment] 2018-04-19 17:58
@mani-ramaswamy will be able to answer this question. 

@chenxumsft, have done any sort of testing on 18.04 ?

**Comment by bpm-ms** [comment] 2018-04-19 18:05
@AnthonyM did we get through the issues with running a cluster inside of the docker container? Your end to end test does that right? If so, even if the host is 18.04, you can build and run inside the container which is still on Xenial....

**Comment by mani-ramaswamy** [comment] 2018-04-19 18:30
18.04 will only be launched end of this month, and we'll investigate and support it in the coming months.

**Comment by nockawa** [comment] 2018-04-19 20:31
@mani-ramaswamy stable version are already available, with RDP protocol compliance which is ideal to use alongside with Windows 10 and Hyper-V. It's a bit sad that it's a matter of months to support it, specially considering that it's the only Linux distribution compatible (as far as I know by reading the documentation).

If it's going to take few months that I don't really have right now to make a decision, can you tell me the ideal workaround to move forward?

I can develop on Windows, test locally, then deploy a on-premise Linux Cluster for production on the 16.04 version?

Please advise, many thanks!

**Comment by mani-ramaswamy** [comment] 2018-04-19 21:59
I understand nockawa. We generally release every 2-3 months, and since we just released 6.2, hence my statement in the coming months. We'll have a better idea once we investigate what's needed.  Until then, as many of our customers do, you can develop on Windows and publish on Linux. Standalone Linux clusters (preview) are also coming soon.

**Comment by nockawa** [comment] 2018-04-19 22:32
So today I can install the on premise Service Fabric on Windows and user Linux Nodes, but Standalone Linux clusters are not released yet, that's right?

I have another question and then I'll stop bugging you: as of today, is it possible to develop Service Fabric service on Linux with VS Code and test them locally? The answer is "yes with Ubuntu 16.04", right?

Thanks for all the information!

**Comment by Pothulapati** [comment] 2018-06-07 16:22
@mani-ramaswamy Is Ubuntu 18.04 Bionic Supported yet? Any update on this?

Thanks.

**Comment by mani-ramaswamy** [comment] 2018-06-07 16:27
It is not supported yet, but we’re investigating it as we plan out the next few months.  We’ll provide an update on this in a couple of weeks. Thanks for your patience.

Best,
Mani

**Comment by MedAnd** [comment] 2018-07-12 00:42
Hi @mani-ramaswamy... friendly ping... any update on this?

**Comment by mani-ramaswamy** [comment] 2018-07-12 00:44
@chenxumsft . Yes MedAnd, we're looking into this - we should have support in the upcoming months.

**Comment by MedAnd** [comment] 2018-07-15 13:40
@mani-ramaswamy @chenxumsft please consider adding support for [Minimal Ubuntu](https://blog.ubuntu.com/2018/07/09/minimal-ubuntu-released)

**Comment by raghav135** [comment] 2018-09-01 16:36
Any updates on this? Is there any workaround for working in latest ubuntu?

Currently the issue is "dot net runtime" has working package for ubuntu bionic, and it has moved to libcurl4, and servicefabric (Xenial) is in libcurl3, not able to proceed.

**Comment by alexeyzimarev** [comment] 2018-10-11 11:56
A long time passed since April...

**Comment by mani-ramaswamy** [comment] 2018-10-11 16:57
This is being worked on - updating the dependencies as well as adequate testing. We're focusing on the next release announced at Ignite which is going out end of this month (6.4) release, and post then the focus will shift to this.  I understand the ask for moving to the latest, but is there any blocking issue on 16.04?

**Comment by alexeyzimarev** [comment] 2018-10-11 18:41
My development machine is Pop!OS and it is the Bionic Beaver. For now, I can only use the container.

**Comment by sagar9004075562** [comment] 2018-10-25 05:32
@mani-ramaswamy can you please provide us with a proper date at which it would be completed ? Some is project are due because of these

**Comment by mani-ramaswamy** [comment] 2018-10-31 18:09
I apologize for the inconvenience, but I don't have an exact date to share. We're targeting H1 CY19 to ship this, but I realize that's a wide time frame. I can loop back with a more narrower time frame in a month or so.

**Comment by mtraudt** [comment] 2018-12-13 19:32
@mani-ramaswamy Do you have any more clarity on the time frame for Bionic support?

**Comment by KiransHub** [comment] 2019-01-05 07:10
I need bionic support :*(

**Comment by MedAnd** [comment] 2019-01-09 10:01
In case others are interested, have been successfully using RDP support on Ubuntu 16.04 for Service Fabric & VS Code development :sunglasses:

**Comment by jfalameda** [comment] 2019-02-09 19:01
Any updates on this?

Thanks.

**Comment by mtraudt** [comment] 2019-03-26 15:02
This question was asked in the most recent Service Fabric Community Q&A and it seems that Ubuntu 18.04 support is not on the short term development roadmap. They made no commitment on the call as to when this might be available.

**Comment by masnider** [comment] 2019-05-09 22:10
> This question was asked in the most recent Service Fabric Community Q&A and it seems that Ubuntu 18.04 support is not on the short term development roadmap. 

Odd. It was under development and should be available soon. https://github.com/microsoft/service-fabric/tree/18.04

**Comment by zhol01825** [comment] 2019-05-14 16:31
Ubuntu 18.04 support is available under "18.04" branch.

Build command
./runbuild.sh -ubuntu18

Additionally you can pass in the -pe option to the script to enable precompiled header 
./runbuild.sh -ubuntu18 -pe

**Comment by MedAnd** [comment] 2019-06-15 14:12
Any update on when Service Fabric for Ubuntu 18.04 will be released? Have some wsl2 R&D pending 😎

**Comment by jfalameda** [comment] 2019-09-11 12:14
Any update on this? Thanks.

**Comment by worldhello126** [comment] 2019-09-11 22:19
we are working on this. Now is under test and bug fixing stage. Target to ship it at end of this year.

**Comment by jfalameda** [comment] 2020-04-06 10:33
Is this merged on master? Is there a package ready for this?

**Comment by worldhello126** [comment] 2020-04-10 21:09
Not yet, We plan to release this with SF 7.1.

**Comment by jfalameda** [comment] 2020-05-18 11:26
Any timeline for this? Is this already supported?

**Comment by worldhello126** [comment] 2020-05-18 16:29
We have release the support with 7.1. but as the Virtus, it require more time to get this rollout to azure portal. We can cooperate with people on this, and hopefully can get some an estimation soon

**Comment by tejasavora** [comment] 2020-08-14 21:56
@worldhello126 Do you know when it will be supported on Ubuntu 20.04 (Focal Fossa)?

**Comment by masnider** [comment] 2021-03-05 21:57
@tejasavora I'm going to close this issue since 1804 has been supported for some time. Support for 20.04 is a separate issue and we will need to provide a timeline in the public roadmap.

**Closed by masnider** 2021-03-05 21:57 UTC
Labels: type-enhancement, type-question
