### ISSUE TITLE
Update Service Fabric source

### ISSUE THREAD

**Issue by tsarpaul** [microsoft/service-fabric#1059] opened 2020-10-14 00:33 UTC
Hi,

Current open-source service fabric version is 6.4 (look at commits here: https://github.com/microsoft/service-fabric/tree/master/src)
When will there be an update? Is the release plan schedule relevant?

**Comment by tsarpaul** [comment] 2020-11-11 11:27
Hi!

Any ETA? :)

**Comment by tsarpaul** [comment] 2020-11-20 01:18
bump

**Comment by LeroyK** [comment] 2020-11-20 10:39
Duplicate of #437

**Comment by craftyhouse** [comment] 2020-12-04 18:09
thanks @LeroyK 
Please follow https://github.com/microsoft/service-fabric/issues/437 for updates on this so we can answer in one place.

**Closed by craftyhouse** 2020-12-04 18:09 UTC
Labels: area-Common
