### ISSUE TITLE
Visual Studio Template with "Configure for HTTPS" is broken

### ISSUE THREAD

**Issue by jackbond** [microsoft/service-fabric#1050] opened 2020-10-05 19:06 UTC
Service Fabric Runtime Version: 

7.1.458.9590

Environment: 

Attempting to run locally with intent of deploying to Azure

If you create a new SF solution with a "Stateless ASP.NET Core" project and select "Configure for HTTPS", the resulting template is woefully incomplete. It's OK for it to be a great starting point, but if you attempt to immediately deploy the project, the deploy fails with ABSOLUTELY ZERO hint of how to resolve the problem. I found this because one of my existing projects started to fail to deploy locally (almost definitely due to a recent SF upgrade.) I was able to get the project to deploy by changing the Endpoint protocol from https to http (and still run.)

Has some additional pre-deployment check been recently added to deployment process when debugging locally?

**Comment by DrEight** [comment] 2020-10-06 11:15
I have the same problem. We have a big SF project that stopped to deploy locally on all the new machines. After days of tests I found that if I change 'https' to 'http' to the service endpoint, everything restart to deploy to the local SF.
There are no errors messages, nothing that can help. 
To reproduce the problem it easy: just create a SF project with a stateless asp.net core and change the endpoint to 'https' in the ServiceManifest.xml. It will stop to deploy to the local SF
I hope that someone can help because we have 2 new developers blocked.

**Comment by moodmosaic** [comment] 2020-10-06 15:32
Run into the same exact issue. This looks like a huge blocker one. /cc @athinanthny, @peterpogorski, @v-mankan

**Comment by ravipal** [comment] 2020-10-06 16:38
We are working on releasing a fix for this issue. The fix should be available on the next update to Visual Studio which is planned for 10/13. Meanwhile, please use this workaround https://github.com/microsoft/service-fabric/issues/1022#issuecomment-696336353

**Comment by jackbond** [comment] 2020-10-06 17:04
@ravipal Is the 10/13 update a preview release?

**Comment by DrEight** [comment] 2020-10-06 18:00
@ravipal thanks it works

**Comment by juho-hanhimaki** [comment] 2020-10-06 18:31
Would be great if any issues this severe would be announced on the SF blog. Wasted an hour or two yesterday on trying to figure out why my projects failed to start debugging.

**Comment by DrEight** [comment] 2020-10-06 20:24
@juho-hanhimaki I agree. I wasted 3 days!

**Comment by jackbond** [comment] 2020-10-06 20:37
@masnider I hate to beat a dead horse on this everyone, but the level of community engagement from the service fabric team is ABSYMAL. Short of their monthly conferences, which quite frankly are a terrible usage of time, their attitude is pretty much, file a service ticket or FO. Seriously, is there anyone who would favor a single monthly group chat over a daily level of engagement here, or on a blog?

The SF team knew about this issue at least two weeks ago. Given that the tooling gave ABSOLUTELY ZERO HELP resolving the issue, there was no way to effectively search this forum for a resolution.

Seriously Matt, is that an acceptable level of engagement?

**Comment by DrEight** [comment] 2020-10-06 21:32
What it shocks me is that nobody even tested the sdk SF release with a https endpoint enabled. The problem can be reproduced with the VS template!

**Comment by ravipal** [comment] 2020-10-07 23:40
@jackbond the fix will be released on both VS 16.7 and 16.8 preview.

**Comment by ravipal** [comment] 2020-10-14 22:18
The fix is released now.

If your machine had the old invalid certificate and causes debugging failure, then run `Get-ChildItem cert:"LocalMachine\My" | Where-Object { $_.FriendlyName -eq "ASP.NET Core HTTPS development certificate" } | Remove-Item` in admin powershell to clean up the invalid certificates. The next F5 will create a valid certificate.

**Closed** 2020-11-23 23:14 UTC
